# Generated by Django 3.1.3 on 2021-03-01 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='User',
            new_name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='stories-07.png', upload_to=''),
        ),
    ]
