# Generated by Django 3.1.3 on 2021-03-01 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_auto_20210301_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='IMG_3260.jpg', upload_to=''),
        ),
    ]
