# Generated by Django 3.1.3 on 2021-03-01 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_auto_20210301_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='stories-07.png', upload_to=''),
        ),
    ]
