# Generated by Django 3.1.3 on 2021-03-14 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_auto_20210301_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='stories.png', upload_to=''),
        ),
    ]
