# Generated by Django 3.1.3 on 2021-03-14 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_auto_20210314_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='stories-07.png', upload_to=''),
        ),
    ]
